{
  "openapi": "3.1.0",
  "info": {
    "title": "DeHoli RESTful API Documentations v1",
    "version": "1",
    "description": "RESTful API Documentations for DeHoli SuperApps",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "name": "Doni Hadimas Aprilian",
      "email": "donihadimas.dev@gmail.com"
    },
    "license": {
      "name": "APACHE 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "url": "http://localhost:5000/{basePath}",
      "description": "The development API server",
      "variables": {
        "basePath": {
          "default": "api/v1"
        }
      }
    },
    {
      "url": "http://192.168.1.7:5000/{basePath}",
      "description": "The staging API server",
      "variables": {
        "basePath": {
          "default": "api/v1"
        }
      }
    },
    {
      "url": "https://apis.deholi.my.id/{basePath}",
      "description": "The production API server",
      "variables": {
        "basePath": {
          "default": "api/v1"
        }
      }
    }
  ],

  "paths": {
    "/categories": {
      "get": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Categories"],
        "summary": "Get all Category",
        "description": "Endpoint for Get All Categories",
        "parameters": [
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/pageSize"
          },
          {
            "$ref": "#/components/parameters/search"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get all categories",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "totalData": {
                      "type": "integer"
                    },
                    "page": {
                      "type": "integer",
                      "format": "int32"
                    },
                    "pageSize": {
                      "type": "integer",
                      "format": "int32"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/categoriesSchemas"
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Example success get all categories",
                    "value": {
                      "success": true,
                      "error_code": null,
                      "message": "Data kategori berhasil ditampilkan",
                      "totalData": 20,
                      "page": "1",
                      "pageSize": "10",
                      "data": [
                        {
                          "_id": "65f1af5e67333070b7bfb124",
                          "categoryName": "Dsadasdas",
                          "totalProductInCategory": 0,
                          "createdAt": "2024-03-13T13:51:26.130Z",
                          "updatedAt": "2024-03-13T13:51:26.130Z",
                          "__v": 0
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Categories"],
        "summary": "Create new categories",
        "description": "Endpoint to Create Category",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateCategories"
              },
              "examples": {
                "jarum": {
                  "description": "Example create category Jarum",
                  "value": {
                    "categoryName": "Jarum",
                    "totalProductInCategory": 3
                  }
                },
                "benang": {
                  "description": "Example create category Benang",
                  "value": {
                    "categoryName": "Benang",
                    "totalProductInCategory": 10
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success create categories",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/categoriesSchemas"
                    }
                  }
                },
                "examples": {
                  "benang": {
                    "description": "Success create java Benang",
                    "value": {
                      "success": true,
                      "error_code": null,
                      "message": "Kategori Berhasil ditambahkan",
                      "data": {
                        "categoryName": "Benang",
                        "totalProductInCategory": 3,
                        "_id": "661a60403e13e6399fff855b",
                        "createdAt": "2024-04-13T10:36:48.460Z",
                        "updatedAt": "2024-04-13T10:36:48.460Z",
                        "__v": 0
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/categories/{id}": {
      "get": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Categories"],
        "summary": "Get all Category",
        "description": "Endpoint for Get one Categories",
        "parameters": [
          {
            "$ref": "#/components/parameters/CategoriesId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get one categories",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "$ref": "#/components/schemas/categoriesSchemas"
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Example success get one categories",
                    "value": {
                      "success": true,
                      "error_code": null,
                      "message": "Data kategori berhasil ditampilkan",
                      "data": {
                        "_id": "65f1af5e67333070b7bfb124",
                        "categoryName": "Dsadasdas",
                        "totalProductInCategory": 0,
                        "createdAt": "2024-03-13T13:51:26.130Z",
                        "updatedAt": "2024-03-13T13:51:26.130Z",
                        "__v": 0
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Categories"],
        "summary": "Update existing categories",
        "description": "Update existing categories in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/CategoriesId"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateCategories"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update categories",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/categoriesSchemas"
                    }
                  }
                },
                "examples": {
                  "benang": {
                    "description": "Success update  Benang",
                    "value": {
                      "success": true,
                      "error_code": null,
                      "message": "Kategori Berhasil diubah",
                      "data": {
                        "categoryName": "Benang",
                        "totalProductInCategory": 3,
                        "_id": "661a60403e13e6399fff855b",
                        "createdAt": "2024-04-13T10:36:48.460Z",
                        "updatedAt": "2024-04-13T10:36:48.460Z",
                        "__v": 0
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Categories"],
        "summary": "Delete existing categories",
        "description": "Delete existing categories in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/CategoriesId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success delete categories",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "$ref": "#/components/schemas/categoriesSchemas"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/employees": {
      "get": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Employees"],
        "summary": "Get all Employees",
        "description": "Endpoint for Get All Employees",
        "parameters": [
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/pageSize"
          },
          {
            "$ref": "#/components/parameters/search"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get all employees",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "totalData": {
                      "type": "integer"
                    },
                    "page": {
                      "type": "integer",
                      "format": "int32"
                    },
                    "pageSize": {
                      "type": "integer",
                      "format": "int32"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/employeesSchemas"
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Example success get all employees",
                    "value": {
                      "success": true,
                      "error_code": null,
                      "message": "Data Karyawan berhasil ditampilkan",
                      "totalData": 20,
                      "page": "1",
                      "pageSize": "10",
                      "data": [
                        {
                          "_id": "65f1af5e67333070b7bfb124",
                          "employeeUsername": "donihadimas",
                          "employeeFullName": "Doni Hadimas",
                          "employeePhoneNumber": "0822961217567",
                          "employeeAddress": "Bandung",
                          "employeeRole": "Administrator",
                          "createdAt": "2024-03-13T13:51:26.130Z",
                          "updatedAt": "2024-03-13T13:51:26.130Z",
                          "__v": 0
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Employees"],
        "summary": "Create new employees",
        "description": "Endpoint to Create Employee",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateEmployees"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success create employees",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/employeesSchemas"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/employees/{id}": {
      "get": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Employees"],
        "summary": "Get one Employee",
        "description": "Endpoint for Get one Employee",
        "parameters": [
          {
            "$ref": "#/components/parameters/Id"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get one Employee",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "$ref": "#/components/schemas/employeesSchemas"
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Example success get one employee",
                    "value": {
                      "success": true,
                      "error_code": null,
                      "message": "Data karyawan berhasil ditampilkan",
                      "data": {
                        "_id": "65f1af5e67333070b7bfb124",
                        "employeeUsername": "donihadimas",
                        "employeeFullName": "Doni Hadimas",
                        "employeePhoneNumber": "0822961217567",
                        "employeeAddress": "Bandung",
                        "employeeRole": "Administrator",
                        "createdAt": "2024-03-13T13:51:26.130Z",
                        "updatedAt": "2024-03-13T13:51:26.130Z",
                        "__v": 0
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Employees"],
        "summary": "Update existing employees",
        "description": "Update existing employees in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/Id"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateEmployees"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update employee",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/employeesSchemas"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Employees"],
        "summary": "Delete existing employees",
        "description": "Delete existing employees in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/Id"
          }
        ],
        "responses": {
          "200": {
            "description": "Success delete employee",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "$ref": "#/components/schemas/employeesSchemas"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/roles": {
      "get": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Roles"],
        "summary": "Get all Roles",
        "description": "Endpoint for Get All Roles",
        "parameters": [
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/pageSize"
          },
          {
            "$ref": "#/components/parameters/search"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get all roles",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "totalData": {
                      "type": "integer"
                    },
                    "page": {
                      "type": "integer",
                      "format": "int32"
                    },
                    "pageSize": {
                      "type": "integer",
                      "format": "int32"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/rolesSchemas"
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Example success get all roles",
                    "value": {
                      "success": true,
                      "error_code": null,
                      "message": "Data Jabatan berhasil ditampilkan",
                      "totalData": 20,
                      "page": "1",
                      "pageSize": "10",
                      "data": [
                        {
                          "_id": "65f1af5e67333070b7bfb124",
                          "rolesName": "Administrator",
                          "permissions": "CRUD",
                          "createdAt": "2024-03-13T13:51:26.130Z",
                          "updatedAt": "2024-03-13T13:51:26.130Z",
                          "__v": 0
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Roles"],
        "summary": "Create new roles",
        "description": "Endpoint to Create Role",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateRoles"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success create roles",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/rolesSchemas"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/roles/{id}": {
      "get": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Roles"],
        "summary": "Get one Role",
        "description": "Endpoint for Get one Role",
        "parameters": [
          {
            "$ref": "#/components/parameters/Id"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get one Role",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "$ref": "#/components/schemas/rolesSchemas"
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Example success get one role",
                    "value": {
                      "success": true,
                      "error_code": null,
                      "message": "Data karyawan berhasil ditampilkan",
                      "data": {
                        "_id": "65f1af5e67333070b7bfb124",
                        "rolesName": "Administrator",
                        "permissions": "CRUD",
                        "createdAt": "2024-03-13T13:51:26.130Z",
                        "updatedAt": "2024-03-13T13:51:26.130Z",
                        "__v": 0
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Roles"],
        "summary": "Update existing roles",
        "description": "Update existing roles in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/Id"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateRoles"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update roles",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/rolesSchemas"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "CategoriesAuth": []
          }
        ],
        "tags": ["Roles"],
        "summary": "Delete existing roles",
        "description": "Delete existing roles in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/Id"
          }
        ],
        "responses": {
          "200": {
            "description": "Success delete roles",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "error_code": {
                      "type": "string",
                      "nullable": true
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "$ref": "#/components/schemas/rolesSchemas"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "CategoriesAuth": {
        "description": "Authentication for DeHoli RESTful API",
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key"
      }
    },
    "parameters": {
      "CategoriesId": {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "Categories id for updated",
        "schema": {
          "type": "string"
        }
      },
      "Id": {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "id for updated",
        "schema": {
          "type": "string"
        }
      },
      "page": {
        "name": "page",
        "in": "query",
        "required": false,
        "description": "The page number for pagination",
        "schema": {
          "type": "integer",
          "nullable": true,
          "default": 1
        }
      },
      "pageSize": {
        "name": "pageSize",
        "in": "query",
        "required": false,
        "description": "The number of items per page",
        "schema": {
          "type": "integer",
          "nullable": true,
          "default": 10
        }
      },
      "search": {
        "name": "search",
        "in": "query",
        "required": false,
        "description": "Search by category name",
        "schema": {
          "type": "string",
          "nullable": true
        }
      }
    },
    "schemas": {
      "categoriesSchemas": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "categoryName": {
            "type": "string"
          },
          "totalProductInCategory": {
            "type": "integer",
            "format": "int32"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "__v": {
            "type": "integer"
          }
        }
      },
      "ArrayCategories": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/categoriesSchemas"
        }
      },
      "CreateOrUpdateCategories": {
        "type": "object",
        "properties": {
          "categoryName": {
            "type": "string"
          },
          "totalProductInCategory": {
            "type": "number"
          }
        }
      },
      "employeesSchemas": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "employeeUsername": {
            "type": "string",
            "required": true
          },
          "employeeFullName": {
            "type": "string",
            "required": true
          },
          "employeePhoneNumber": {
            "type": "string",
            "required": true
          },
          "employeeAddress": {
            "type": "string",
            "required": true
          },
          "employeeRole": {
            "type": "string",
            "nullable": true
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "__v": {
            "type": "integer"
          }
        }
      },
      "CreateOrUpdateEmployees": {
        "type": "object",
        "properties": {
          "employeeUsername": {
            "type": "string",
            "required": true
          },
          "employeeFullName": {
            "type": "string",
            "required": true
          },
          "employeePhoneNumber": {
            "type": "string",
            "required": true
          },
          "employeeAddress": {
            "type": "string",
            "required": true
          },
          "employeeRole": {
            "type": "string"
          }
        }
      },
      "rolesSchemas": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "rolesName": {
            "type": "string",
            "required": true
          },
          "permissions": {
            "type": "string",
            "required": true
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "__v": {
            "type": "integer"
          }
        }
      },
      "CreateOrUpdateRoles": {
        "type": "object",
        "properties": {
          "rolesName": {
            "type": "string",
            "required": true
          },
          "permissions": {
            "type": "string",
            "required": true
          }
        }
      }
    }
  }
}
